# Generated by Django 2.1.7 on 2019-02-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_doc_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='doc_pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.Colaborador'),
            preserve_default=False,
        ),
    ]
